### ISSUE TITLE
[FEAT] 실시간 집계 업데이트 기능 및 공부 기록 저장 시 값을 대입하는 방식으로 변경

### ISSUE THREAD

**Issue by rlfrkdms1** [woohaengshi/backend#72]
# ⚙️ ISSUE
-  실시간 집계 업데이트 기능 및 공부 기록 저장 시 값을 대입하는 방식으로 변경

# 📄 To-Do
- [ ]  실시간 집계 업데이트 기능 
- [ ] 공부 기록 저장 시 값을 대입하는 방식으로 변경

**Comment by khwoowoo** [comment]
아직 작업 안 한 것 같아서 제가 작업해봤는데 혹시 봐줄 수 있을까요?? 매월 1일, 매주 월요일에는 초기화하는 작업 필요할 것 같아서 그거 작업하는 김에 같이 했습니다!

**Comment by rlfrkdms1** [comment]
엇 .. 저 어제 이거 다 하고 갔는데 ㅜ PR 올리셔서

**Comment by rlfrkdms1** [comment]
컹스 ㅠ
<img width="677" alt="스크린샷 2024-08-17 오후 3 55 56" src="https://github.com/user-attachments/assets/199655b6-f04b-41e9-bacf-66f3c5adfd13">
